#pragma once

#include <windows.h>
#include <psapi.h>
#include <d2d1_3.h>
#include <d3d11_4.h>
#include <dwrite_3.h>
#include <dxgi1_6.h>
#include <microsoft.ui.xaml.media.dxinterop.h>
#ifdef GetCurrentTime
#undef GetCurrentTime
#endif
#include <cstdint>
#include <chrono>
#include <algorithm>
#include <cwctype>
#include <ctime>
#include <sstream>
#include <optional>
#include <mutex>
#include <string>
#include <string_view>
#include <thread>
#include <vector>
#include <unknwn.h>
#include <winrt/Microsoft.UI.Dispatching.h>
#include <winrt/Microsoft.UI.Input.h>
#include <winrt/Microsoft.UI.Xaml.h>
#include <winrt/Microsoft.UI.Xaml.Automation.h>
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#include <winrt/Microsoft.UI.Xaml.Input.h>
#include <winrt/Microsoft.UI.Xaml.Media.h>
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#include <winrt/Microsoft.UI.Xaml.Navigation.h>
#include <winrt/Microsoft.UI.Text.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.UI.h>
#include <winrt/Windows.System.h>
